didymo/OnkoDICOM

- src/Controller/interPageController.py
- src/Model/Pyradiomics.py
replaced is with == for comparison to '' per flake8 failures
> replaced is with == for comparison to '' per flake8 failures

- src/View/mainPage.py
sort ascending on selected isodose washes so that the larger lower dose isodose washes don't cover up the smaller higher dose isodose washes
> sort ascending on selected isodose washes

- src/View/ProgressBar.py
And including alternative conditional logic for multiprocessing vs. single processing of DVH.
> Add sort images by displacement along stack

- src/View/ProgressBar.py
deleting the excess lines from conditional branch
> removed unexpected merge from earlier PR

- src/Controller/interPageController.py
this is a bug fix (the app would core dump due to wrong signature for
creating MainWindow).
some reformatting based on my settings in (VS) code
> constructing PatientDictContainer and passing that in to MainWindow

- src/Model/Anon.py
> added docstring annotation to some of the functions

- src/Model/Anon.py
the pythonic way of determining if a key is in a dict is
if my_key in my_dict
> removed the hasattribute function

- src/Model/ROI.py
> use ndarray and np.matmul() instead of the deprecated matrix class

- src/Model/Anon.py
- test/test_model_anon.py
prefix with _ to make all functions private other than anonymize()
change to names that more clearly indicate purpose
added docstring to more functions
eliminated some unused imports
eliminated use of LOAD_DCM function whose purpose had essentially been eliminated in some previous change from re-reading DICOM files to indexing in to dictionary of patient's DICOM objects.
eliminated indexing in to dictionary of patient's DICOM objects in loops that iterated on the dictionary of patient DICOM objects
by iterating on the items (getting the key and value simultaneously)
reworded text in some of the print statements for clarity
> refactor by renaming functions

- src/Controller/AddOnOptionsController.py
fixed > vs. >= bug for number of items/columns of data in the reidentification file
patientHash.csv
automated reformatting by black.
> fixed bug for number of items/columns of data 

- src/View/mainpage/StructureTab.py
Removing print statement that was accidentally left in from previous commit.
> Removed a print statement used for testing

- README.md
> add newline between the two pip install commands

- src/View/ProgressWindow.py
> Spelling correction.

- src/Controller/GUIController.py
- src/Model/InitialModel.py
- src/View/mainpage/MainPage.py
This change compartmentalizes functions carried out during the initialization of the main window in order to ensure that methods don't become too bloated by containing functionality that could be located elsewhere. The model initialization has been moved to a more appropriate location in Model package.
> Moved model initialization out of the main window's UI setup.

- src/View/mainpage/DicomView.py
This restores information that was missing from the main window restructure regarding metadata of the currently selected slice.
> Added metadata information to DicomView.

- src/View/mainpage/IsodoseTab.py
> Isodose tab reworked to reduce code repetition

- .github/workflows/pythonapp.yml
- requirements.txt
- src/Model/Worker.py
- test/test_model_worker.py
Adds in unit testing for the Worker class to ensure that it will be instantiated properly, that the correct values are returned from the worker, and that exceptions are properly handled.
Also adds in a fix where the program would crash if progress_callback kwarg were set to False.
Added explanations of variables in exception handling part of Worker class.
> Worker tests

- src/Model/Anon.py
just before pseudonymising
pymedphys issue https://github.com/pymedphys/pymedphys/issues/1246 
pymedphys PR https://github.com/pymedphys/pymedphys/pull/1247
> workaround for pymedphys: strip the UTC information from AcquisitionDateTime in place

- requirements-without-deps.txt
- src/Model/Anon.py
Updated version of pymedphys handles UTC offsets in DT, DA, and TM,  and corrects Decimal String (DS) pseudonymising.
But avoid pseudonymising Patient Weight and Patient Size (height) even though DS is handled correctly as of pymedphys 0.35.0
> Update pymedphys version

- legacy/src/View/mainpage/MainPage.py
- src/Model/InitialModel.py
the values
default to soft tissue values from default CT LUT  if they are not found in the DICOM data
> check for presence of WindowWidth and WindowCenter before accessing 

- src/Model/ImageLoading.py
- src/View/ImageLoader.py
- src/View/mainpage/DVHTab.py
- src/View/mainpage/DicomView.py
For reasons unknown, a couple modules have been importing numpy through the pandas package. This branch corrects and cleans up the imports of the culprit modules.
> Corrected numpy being imported via pandas package

- test/conftest.py
- test/test_model_configuration.py
- test/test_view_dvh_tab.py
- test/test_view_first_time_welcome_window.py
this PR adds a unit test for DVH tab in OnkoDICOM.
> add test for dvh tab

- src/Controller/GUIController.py
- src/Controller/TopLevelController.py
- src/View/mainpage/MainPage.py
The current main window does not update its UI when a new patient is opened. This PR fixes this problem. 
In relation to issue #1563 on Team23's Redmine.
> Bug Fix: Update main window when a new patient is loaded

- src/View/ProgressWindow.py
- src/View/mainpage/DVHTab.py
Calculate DVHs Messagebox now displays "No" & "Yes" buttons in respective order across platforms.
> Bug Fix: Calculate DVHs Messagebox button ordering 

- data/csv/organName.csv
This PR addresses Bug #1639 on Redmine.
> Update organ name csv file

- setup.py
- src/Model/Anon.py
- src/Model/CalculateDVHs.py
- src/Model/CalculateImages.py
- src/Model/Configuration.py
- src/Model/DICOMDirectorySearch.py
- src/Model/DICOMStructure.py
- src/Model/DICOMWidgetItem.py
- src/Model/GetPatientInfo.py
- src/Model/ImageLoading.py
- src/Model/InitialModel.py
- src/Model/Isodose.py
- src/Model/PatientDictContainer.py
- src/Model/ROI.py
- src/Model/Singleton.py
- src/Model/Worker.py
This PR updates the format of all files in src/Model to be compliant with PEP-8. This renaming variables and wrapping lines to be complaint. No changes to code functionality, this is intended to increase readibility.
> Updated src/Model files for PEP-8 compliance.

- src/Controller/AddOnOptionsController.py
After user clicks into Anonymisation button, a anonymized patient item is created but it is not updated to the anonymised patient list in add-on options
> fix anonymized patient list can not display upon anonymisation

- src/Controller/ActionHandler.py
- src/Controller/AddOnOptionsController.py
- src/Controller/GUIController.py
- src/Controller/TopLevelController.py
- src/View/AddOnOptions.py
- src/View/ImageFusion/ImageFusionAxialView.py
- src/View/ImageFusion/ImageFusionCoronalView.py
- src/View/ImageFusion/ImageFusionProgressWindow.py
- src/View/ImageFusion/ImageFusionSagittalView.py
- src/View/ImageFusion/ImageFusionWindow.py
- src/View/mainpage/DicomAxialView.py
- src/View/mainpage/DicomCoronalView.py
- src/View/mainpage/DicomGraphicsScene.py
- src/View/mainpage/DicomSagittalView.py
- src/View/mainpage/DicomTreeView.py
- src/View/mainpage/DicomView.py
- src/View/mainpage/DicomView3D.py
- src/View/mainpage/MainPage.py
This PR is to address the bugs [1897 ](https://redmine.didymodesigns.com.au/issues/1897), [1898](https://redmine.didymodesigns.com.au/issues/1898) and [1903](https://redmine.didymodesigns.com.au/issues/1903) related to Image Fusion (except for ROI and Windowing - this will still need to be implemented).
A summary of the fixes:
- Zoom in/out working
- Crosshairs work
- Message box has been enlarged
- Able to delete window
- Opening a new patient after Image Fusion from a previous patient, does not affect the selection of the moving image of new patient
Work to be done still
- Windowing to be applied on Image Fusion
- ROIs not being displayed
> Fix - Image Fusion 

- src/Model/SUV2ROI.py
- src/View/AddOnOptions.py
- src/View/OpenPatientProgressWindow.py
- src/View/mainpage/MainPage.py
This PR makes multiple user experience improvements. These improvements are:
- A reason for failure is now given if the SUV2ROI process fails.
- The footer on the main page has been updated to read "@OnkoDICOM2021".
- The clinical data CSV page in the add-on options menu has had its text updated.
- "RT DOSE" in the calculate DVH prompt that appears when OnkoDICOM loads a patient has been changed to "RTDOSE".
> UX Improvements

- src/Model/ROI.py
This PR fixes ROI DIFFERENCE operation for the case where ROI2 contains multiple polygons where some polygons are inside ROI1 and the others are outside.
> Bug: ROI Manipulate

- src/Model/CalculateImages.py
This PR fixes the bug where bytes did not account for colored pixels.
> Bug: bytes per line for colored images

- src/Model/Radiomics.py
This PR addresses the issue of the NUL file not being removed during the batch PyRad2Pyrad-SR conversion.
> Bug fix: removal of NUL files

- src/Model/ROI.py
This PR fixes the crash when doing ROI difference with an empty ROI
> fix roi difference with empty roi

- src/View/mainpage/MainPage.py
This is a small PR that fixes SUV2ROI failure when it attempts to refresh the screen.
> Bug Fix: SUV2ROI failure

- src/Controller/BatchProcessingController.py
- src/Model/batchprocessing/BatchProcessFMAID2ROIName.py
- src/Model/batchprocessing/BatchProcessROIName2FMAID.py
- src/Model/batchprocessing/BatchProcessROINameCleaning.py
- src/View/BatchProcessingWindow.py
- src/View/batchprocessing/BatchSummaryWindow.py
- src/View/batchprocessing/FMAID2ROINameOptions.py
- src/View/batchprocessing/ROINameCleaningOptions.py
Functionality so that if the Name is changed to FMA ID it can be changed back with FMAID2ROIName.py. GUI for this function is also in this PR.
Update for ROINameCleaningOptions.py so that the volume prefix is displayed in the new name section of the table and can be edited.
I will not add logging to this PR.
edit:
PR #209 logging will be removed as per the logging meeting.
> FMAID2ROIName.py function and update for ROINameCleaningOptions.py

- src/View/mainpage/DrawROIWindow/Drawing.py
- src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
- test/test_view_drawing.py
Adding a Breadth First Search (BFS) functionality to the draw (fill) button for the 2D semi-automated contouring. This will draw the ROI for the single slice (2D) with a full 3D fill to come later.
> 2D semi-automated contouring

- data/csv/volumeName.csv
- src/Model/batchprocessing/BatchProcessROINameCleaning.py
- src/View/batchprocessing/ROINameCleaningOptions.py
These changes are to fix the errors that Dr Miller has been facing with ROINameCleaning in the batchprocessing section.
> ROINameCleaning fixes

- src/Controller/ROIOptionsController.py
- src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
- src/View/mainpage/MainPage.py
- src/View/mainpage/StructureTab.py
- test/test_view_drawing.py
Refactor of the draw ROI window, controller and main page so that the popup can instead be displayed in the main window.
This includes testing and logging :)
> DRAW_ROI_GUI_REFACT_#2437

- src/Controller/BatchProcessingController.py
- src/Model/batchprocessing/BatchProcessPyRad2CSV.py
- src/View/BatchProcessingWindow.py
- src/View/OpenPatientWindow.py
- src/View/batchprocessing/BatchSummaryWindow.py
- test/test_model_batch_processes.py
PyRad2CSV is being changed so that it reads the Pyrad-SR file created in the function Pyrad2Pyrad-SR instead of calculating the CSV file with pyradomics as it did previously. This allows for quicker processing and removal of redundant calculations.
> PyRad2CSV change so that it uses the PyRad-SR file created in Pyrad2Pyrad-SR

- src/Controller/BatchProcessingController.py
Minor fix of the pop-up message
> minor fix of the success message from machine learning.

- src/Model/ForceLink.py
- src/View/OpenPatientWindow.py
Force link fixed. Now works with example files on redmine
> Force Link

- src/Model/batchprocessing/BatchProcessMachineLearning.py
- src/Model/batchprocessing/batchprocessingMachineLearning/MachineLearningTrainingStage.py
- src/Model/batchprocessing/batchprocessingMachineLearning/Preprocessing.py
Added Train set to Confusion matrix.
Very small update.
> Machine learning very small update

- .github/workflows/pythonapp.yml
- src/Controller/MainPageController.py
> declare FEATURE_TOGGLE_PSEUDONYMISE and set true for successful import

- src/View/mainpage/MainPage.py
- src/_version.py
> [Enhancement] Display version in footer

- pyproject.toml
> Revert "Poetry"

- .github/workflows/pythonapp.yml
- dev-requirements.txt
However, pytest with certain UI related cases are not supported/stable on Windows 2022, especially python 3.10.
> Build and test on Windows

- .github/workflows/pythonapp.yml
- poetry.lock
- pyproject.toml
> Update version of pymedphys, eliminate pyradiomics from pyproject and specify post install of pyradiomics==3.0.1

- src/Model/Anon.py
- test/test_model_anon.py
anon_file_name: function to check and modify to name the file name valid 
automated test include
> Update Anon.py - Validate File Name

- src/View/mainpage/WindowingSlider.py
apply guard, check bin index is within range  prior to indexing in to…histogram
> Check index in range  before  incrementing

- pyproject.toml
- src/View/mainpage/DicomView.py
- src/View/mainpage/WindowingSlider.py
- src/_version.py
just want to make sure nothing breaks when updating the pyproject.toml project version.
will follow up with work on getting transect line to display
> fix transect line display and bump version to 0.6.0-dev1

- src/View/StyleSheetReader.py
- src/View/WindowingUI.py
- src/View/batchprocessing/DVH2CSVOptions.py
- src/View/mainpage/MLTab.py
- src/View/mainpage/MLTestResultsWindow.py
- src/View/mainpage/MainPage.py
- src/View/mainpage/ManipulateROIWindow.py
- src/View/mainpage/RenameROIWindow.py
Redmine Ticket [#3051](https://redmine.didymodesigns.com.au/issues/3051)
> created class for the style sheet to stop people repeating this code
