.github/workflows/pythonapp.yml, src/View/ProgressBar.py, test/test_model_roi.py
adds the SOP Class UID for RT Ion Plan as a consumable 'rtplan' Dataset given the current usage of the Dataset in OnkoDICOM (tested against private copy of an RT Ion Plan based dataset).
Adds a simple unit test for Model.ROI.calculate_matrix() to test directory
Adds a github action using the default pythonapp.yml from github, which passes in part because the unit test ensures that there are more than zero tests.
Accepting this Pull Request will result in future OnkoDICOM Pull Requests triggering the action and enforcing flake8 and pytest
=> Add rtionplan support redux

src/View/mainpage/DicomTree.py
Due to the hardcoded nature of the DICOM tree tab, when files such as RTSTRUCT and RTDOSE are not loaded into the program they will still display as options in the dropdown menu. Selecting these will crash the program. Additionally, all image files will be labelled as CT slices, even if the slices are not CT images.
So I put combobox.addItem RTDose and RTStruct in mainwindow.has_rtss condition, that solved the above error.
=> Fix DICOM Tree tab displays files not part of dataset

src/View/mainpage/MenuBar.py
In MenuBar.py, the use of confirmation_dialog was originally outside of if-else statement that checking has_rtss.
So when selecting ROI Delete option, if the patient has_rtss, the program will crash because confirmation_dialog is not referenced.
=> [ROIDelete] MenuBar.py: Local variable 'confirmation_dialog' referneced before assignment

src/View/OpenPatientWindow.py, src/View/mainpage/MainPage.py
On Open Patient Window, Users can now drop directories in the input field and commence the DICOM search.
On the main page, there is now a section that allows for files to be dropped with the file path printed to console.
=> Adding in Drag and Drop Functionality

main.py, src/Controller/GUIController.py, src/Controller/TopLevelController.py
This allows the end user to drag and drop a folder onto OnkoDICOM's script in order to skip the welcome window and have that folder loaded automatically.  This has been tested to work on main.py _and_ the windows executable.
=> Main script now accepts default directory from drag and drop

src/View/mainpage/MainPage.py, src/View/mainpage/PatientBar.py
Minor alignment fixes to the PatientBar class.
Before:
After:
=> Adjustments to PatientBar alignment.

src/Controller/ActionHandler.py, src/View/mainpage/DicomView.py
The Windowing button in the tool bar and menu bar are now populating with items correctly. As a consequence of the windowing buttons now working, I noticed that the DICOMView never actually updated according to changes made to the pixmaps. That has also been corrected.
=> Fix windowing action

src/View/mainpage/StructureTab.py
This branch introduces the following:
- Saving RTSTRUCT no longer asks for a user file path. Instead, it now overwrites the existing RTSTRUCT file. The user is warned of this when they save.
- Fixed a bug that made multiple modified indicators appear on top of eachother when making multiple changes to the structures.
- The structure modified indicator now appears above the ROI Draw/Delete buttons.
=> Improvements to saving modified RTSTRUCT.

src/Model/ROI.py
The ROI module is looking for the ReferencedImageSequence in create_roi
The pre-populated rtss did not have that set (only the Contour Image Sequence was set)
=> Add ref img seq on create / prepopulate rtss

src/Controller/ActionHandler.py, src/View/mainpage/MenuBar.py, src/View/mainpage/Toolbar.py
When an RTSTRUCT is present, a new Save Structure Changes button has been added to the toolbar and menubar. This is an alternative way for the user to save structures beyond the current options of clicking the modified structures indicator, or closing the current patient session.
=> Added save action

src/View/ImageLoader.py, src/View/mainpage/DVHTab.py, src/View/mainpage/StructureTab.py
When adding a contour to an existing ROI, or creating a new region entirely,the DVH graph will not reflect this changes. Until the functionality to re-calculate the DVH is implemented, the user will for the time being be informed that the modified DVHs are not up to date with the calculation.
=> User is now informed when DVH values are outdated after ROI draw.

src/Model/ImageLoading.py, src/Model/Worker.py, src/View/OpenPatientWindow.py, src/View/ProgressWindow.py
R#1020
The Worker class has been used as a portable way of deploying and running any function in a new PyQt thread utilizing the Qt's QThreadPool and QRunnable classes, and connecting to the thread's progress/results/errors as PyQt signals.
In the previous implementation of the Worker class, any function called by the Worker class would require the called function to have a `progress_callback` parameter, representing the progress signal of the Worker class. This change makes it so that any function can be run with or without the parameter. If the Worker instance wants to emit a progress signal, it can do so by doing the following:
* In the instantiation of the worker class, set the keyword argument `progress_callback=True`. For example:
`worker = Worker(slow_calc_fn, list_of_inputs, …
=> Improvements to multi-threading Worker class

requirements-without-deps.txt, src/Model/Anon.py
will work with either 0.33 or 0.34 and later pymedphys
fails fast if pymedphys import fails in any way rather than falling back to the legacy anonymisation
used black for formatting, so some "format only" changes (mostly removal of white space at the end of a line).
=> Workaround pymedphys anonymise api changes

.github/workflows/pythonapp.yml, README.md, pre-requirements.txt, requirements-without-deps.txt, requirements.txt
Due to issues with the way pip works, despite Cython being listed as a dependency for PyWavelets it does not install automatically. There is a similar issue with numpy. There was also an issue being caused by PyRadiomics not being installed without dependencies. For these reasons, the requirements have been restructured to have pre-requirements. These will be installed, and then the regular requirements will be installed. The GitHub Action for testing has been updated to accommodate this change.
Additionally, the README has been updated to provided better and more up-to-date information.
=> Rejig requirements

src/Model/ImageLoading.py
Sample data had Points (of interest) as the first few ROIs, and those did not have a contour sequence (so no contour image sequence contained within).
Further work to address checking that the data is "suitable for use" is warranted.
The POIs will show in OnkoDICOM, but if the user selects the checkbox, a warning message will appear in the terminal.
I did not test through to "able to produce radiomics", so complete end to end testing with such sample data is needed.
=> Fix inappropriate dependence on first contour sequence

src/Model/ROI.py, src/View/mainpage/DeleteROIWindow.py, src/View/mainpage/DrawROIWindow.py, src/View/mainpage/RenameROIWindow.py
R#1021
These changes show the user visual feedback when Drawing, Deleting, or Renaming ROIs. Previously, the window would freeze while the RTSTRUCT would be updated, however that is unideal and can lead to users believing the program is no longer working. Now, a small window will pop up advising the user that some process is being run in the background and to wait for its completion.
=> Improved feedback when modifying RTSTRUCT

.gitignore, OnkoDICOM-Windows.spec
This change identifies and fixes the present issues with compiling on Windows using the .spec file. The issues revolved around Pyinstaller not identifying files necessary for the execution of OnkoDICOM, and therefore not copying them to the distribution directory. A critical numpy DLL is included in this list of missed files.
This change adds a workaround that directly specifies to Pyinstaller which additional files need to be included in the distribution.
=> Fix windows spec

src/View/mainpage/DicomTreeView.py
This commit fixes an error when the program is missing rt files. The old code assumed the rt files were all included in loading and hard coded the indexes in. This code removes the hard coding and adds an array to track which rt files are present.
=> Fixed bug with hard-coding indexes and missing rt files

src/View/ImageLoader.py, src/View/OpenPatientWindow.py
This PR:
- disable user from selecting multiple patients to open.
- display warning messages for when RTStruct, RTImage or RTPlan files are missing
=> Feature: disable mutiple patient selection and warning messages for missing files

res/stylesheet-win-linux.qss, res/stylesheet.qss
Change the color of the error text when missing DICOM files from black to red so that the error is distinguished from the other text.
=> Red error text in QTreeView (OpenPatientWindow)

src/Model/DICOMDirectorySearch.py, src/Model/DICOMStructure.py
The current Directory Search function in the open patient window is slow and not fault-tolerant. This PR can improve the search function by:
- Remove counting "total files" since it walks through all files in the directory to get the total number of files which doubles the running time
- Change DICOMStructure arrays to hashmaps to get O(1) search instead of O(n)
- Ignore hidden directories to avoid reading configuration and system files which can cause the program to crash
=> Feature: Optimisation for Directory Search function in Open Patient Window

src/Controller/MainPageController.py
1. Fix the argument type of setPen function (from QColor -> QPen). The argument type is different between PyQT5 and PySide6. 
2. Specify the correct argument button0 used in QMessageBox so that the correct overloaded function is called.
=> Bug Fix: Transect 

src/Controller/AddOnOptionsController.py
Changed names of slots in file AddOnOptionsController to work with PySide's slot signature to avoid the following errors received on Linux: 
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_customContextMenuRequested_Window(QPoint)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_customContextMenuRequested_Organ(QPoint)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_customContextMenuRequested_Volume(QPoint) 
Also changed method names to align with the naming conventions.
=> Renamed slots and method names

src/Controller/AddOnOptionsController.py, src/Controller/TopLevelController.py, src/View/mainpage/MainPage.py
The open patient window will no longer refresh the directory when the oncologist wants to open a new patient.
This is done following the comment from Dr. Andrew Miller.
> For Patient File directory; I tested this today.
When I start, there is a directory reading process to find all patients in the default file. [good]
I opened a patient, did what I must and then went to select a new patient.
The Patient File directory opened again, and the whole directory reading process occurs again. [?good practice but bad for time]
I would like to have a discussion about the usefulness of displaying the patient list as it was previously. By the end of this year, the only change in directory structure is going to be the addition of RTSTRUCT and DICOM-SR files. Other files are already ignored.
What are …
=> Disable directory refresh in open patient window

src/View/OpenPatientWindow.py
The wrong image type in Open Patient Window prevents the application from opening MR scan. 
In relation to issue #1561 on Team23's Redmine.
=> Wrong image type in Open Patient Window

src/View/mainpage/StructureWidget.py
This PR addresses issue number #1564: OnkoDICOM malfunction - OnkoDICOM_Video2
The ROI rename function does not appear because in PySide6, functions named `exec_ `(classes QCoreApplication, QDialog, QEventLoop) have been renamed to `exec`.
=> Bug#1564: ROI rename window not shown

src/Controller/ActionHandler.py, src/View/mainpage/MainPage.py, src/View/mainpage/StructureWidget.py
This PR addresses issue number #1579: The +- magnifiers are not working
I'm not sure why this is an issue in PySide6 and not in PyQt5, but it is because the class ActionHandler called the zoom_in and zoom_out function from class dicom_view.
It is better to wrap the zoom functions inside class MainPage anyway to comply with the Encapsulation principle in OOP.
=> Bug#1579: zoom magnifiers not working

src/View/OpenPatientWindow.py
The wrong image type in the Open Patient Window prevents the application from opening PET scans.
In relation to issue #1565 on Onko's Redmine.
=> Bug fix: cannot open a PET (PT) scan

src/View/mainpage/MainPage.py
This PR fixes the following issue: (Bug #1600 on Team23's Redmine Page)
Please follow the following steps to reproduce the problem:
1. Open a patient with RTDOSE and RTSTRUCT (Calculate DVH)
2. Then open another patient without RTDOSE and/or RTSTRUCT
3. Then perform any functionality related to RTDOSE and/or RTSTRUCT in the new patient. (E.g. Change Line & Fill Configuration)
4. Application fails
=> Remove old QWidgets in Main Window

test/test_view_isodoses_tab.py
This PR adds a unit test for the Isodoses tab in the main window. It asserts that the correct doses are selected and deselected, and therefore drawn and not drawn when the corresponding checkboxes in the Isodoses tab are checked and unchecked. This commit assumes the existence of a test file in /`test/testdata/DICOM-RT-TEST`.
=> Product Backlog #1469: Addition of Isodoses Tab Unit Test

src/Controller/GUIController.py, src/Controller/TopLevelController.py, src/View/mainpage/MainPage.py
This PR addresses the Bug #1623 on Team23's Redmine Page. 
Please follow the following steps to reproduce the problem: 
1. Open a patient without a RTSTRUCT file. 
2. Open another patient with a RTSTRUCT file. 
3. The "Save RTSTRUCT" option is not available on the toolbar indicating that the toolbar and menu haven't been updated when opening a new patient.
=> Bug Fix: Update Toolbar and Menu

src/View/mainpage/DicomView.py, src/View/mainpage/StructureTab.py, src/View/mainpage/StructureWidget.py
This PR addresses bug #1582 in OnkoDICOM:
- Display ROI borderline using QPen, even when roi_line_fill is set to 0% in Add-on option
- Retain ticks and background color of previously checked boxes after Structure Tab is updated
- Remove duplicates in roi_id list in patient_dict_container when roi_line_fill set to > 0% to avoid permanent display of original specification
=> ROI display inactivated by Line configuration change

src/View/mainpage/DicomView.py, src/View/mainpage/DrawROIWindow.py
Fixed:
- Opening DrawROI window whilst isodoses are selected caused the program to crash 
- DrawROI displaying ROI or Isodoses
=> Draw ROI window fix

res/stylesheet-win-linux.qss, src/View/OpenPatientWindow.py
Fixed: 
- Patient will only be highlighted in purple if the patient is selected and checked. 
- Patient that is only selected and not checked will have a purple border. 
- Changed the patient's tree's signal from itemChanged to itemClicked, avoids repetitive calls as selecting a child leaf will change the parenting leaf, causing the same method to be called repetitively.
=> Fix: Patient Selection Highlight

src/Model/ImageLoading.py
There was an unhandled exception where slice_key could be 0 when calculating thicknesses for ROI that contain one contour.
=> Bug/Fix: Bug #1622 

src/View/mainpage/DeleteROIWindow.py, src/View/mainpage/DrawROIWindow.py
This PR addresses the following issues on Linux systems when opening a Draw ROI window:
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_zoom_out_clicked()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_backward_clicked()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_forward_clicked()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_box_draw_clicked()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_draw_clicked()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_preview_clicked() …
=> Bug/Fix Draw ROI window

src/View/mainpage/RenameROIWindow.py
Users can now rename ROI's to the entered name by pressing 'Enter', instead of hitting the tab twice, then press enter.
=> Rename ROI by pressing 'Enter'

src/Controller/AddOnOptionsController.py
Changed more slot function names from snake_case to camelCase to avoid the following conflicts with the QT framework:
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_custom_context_menu_requested_window(QPoint)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_custom_context_menu_requested_organ(QPoint)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_custom_context_menu_requested_volume(QPoint)
=> Changed more slot names to avoid conflicts 

requirements.txt
The branch we have been using for matplotlib PySide6 support is now merged. This PR updates `requirements.txt` and update the pipeline. When matplotlib releases version 3.5.0, we should change it to `matplotlib==3.5.0` for a stable version.
=> fix matplotlib support issue

src/Controller/ActionHandler.py, src/Controller/MainPageController.py
When opening multiple patients, only the first patient that was opened would be anonymised, regardless of what was currently opened.
This was caused by the class `MainPageCallClass`, which wraps and controls the anonymisation function, not being updated whenever a new patient was open. Therefore, the file path and dataset being passed into the anonymisation function would always be the file path and dataset of the first patient that was opened.
This PR fixes this by creating a function to reload and update file path and dataset information in `MainPageCallClass`, and calling this function before anonymising the currently opened patient.
=> Fix anonymising saving to wrong directory

.github/workflows/pythonapp.yml
This PR addresses the issue where the pipeline fails while installing required packages. 
The fix is to perform apt-get update before installing the packages. 
> The sudo apt-get update command is used to download package information from all configured sources.
The sources often defined in /etc/apt/sources.list file and other files located in /etc/apt/sources.list.d/ directory.
So when you run update command, it downloads the package information from the Internet. It is useful to get info on an updated version of packages or their dependencies.
=> Fix Pipeline Fail

src/View/util/QVTKRenderWindowInteractor.py
This PR resolves bug #1895 on onko redmine
- Fix crash when user interacts with 3D view using mouse wheel
=> fix crash when using mouse wheel on 3D view

requirements.txt
This PR fixes the style_sheet breaking OnkoDICOM with the new version of PySide by fixing the version of PySide6 to 6.1.2
=> Update Requirements to fix styling issue

src/Controller/GUIController.py, src/Controller/TopLevelController.py, src/Model/PTCTDictContainer.py
This PR adresses the issue where multiple instances of OpenPTCTPatientWindow selection can be loaded, when loading the initial data in PTCTDictContainer, it sets all other variables as none, in case the container is populated before the initial values are set.
=> Bug: Fix Segmentation Fault

res/stylesheet-win-linux.qss, res/stylesheet.qss, src/View/AddOnOptions.py, src/View/BatchProcessingWindow.py, src/View/batchprocessing/CSV2ClinicalDataSROptions.py, src/View/batchprocessing/ROINameCleaningOptions.py
This PR fixes multiple things, mainly to do with batch processing:
- CSV files with the extension `.CSV` can now be opened in Batch CSV2ClinicalData-SR. 
- Batch ROI Name Cleaning for ROIs with standard prefixes has been fixed and now works properly. Users are given the option to enter in a new name for ROIs with standard prefixes (eg. ISO, SUV). The new name is then prefaced by the same prefix, and used to rename the ROI.
- Text has been added to the standard organ names add-on options window that directs users to a web page containing all standard organ names if they wish to add more. This URL is clickable.
=> Bug Fixes: Batch Processing 

src/Controller/ActionHandler.py, src/Model/PTCTModel.py, src/Model/Windowing.py, src/View/WindowingUI.py, src/View/mainpage/MainPage.py
This PR adds the ability to specify the views to apply a window on:
- If DICOM view is the only active view, then windowing is automatically applied to DICOM view
- If PET/CT view or Image Fusion view is active, a popup will open with checkboxes for each active view
- The checkboxes can be selected and multiple views can be updated at the same time
This PR also moves the windowing function in src.Controller.ActionHandler to src.Model.Windowing to comply with MVC
=> Fix: Select Views for Windowing

src/Controller/AddOnOptionsController.py, src/Controller/GUIController.py, src/Model/ImageFusion.py, src/View/addons/ImageFusionAddOnOption.py, src/View/mainpage/MainPage.py
This PR is to fix issues:
1. Key and Value error when attempting to use the Study Description as the fixed and moving labels in the addon options, resulting in a crash.
2. Matrix not existing when attempting other registration methods besides "rigid".
To elaborate key point 2: a rigid matrix can be calculated when _rigid_ mode is selected. Other modes did not result in a rigid matrix with current calculations. DICOM standards allow the Spatial Registration Object to save RIGID, RIGID_SCALE and AFFINE matrices.
This PR also introduces the fix to update the fixed image and moving image labels when opening a new patient.
=> Bug Fix: Addon Options

requirements.txt
This PR changes the required version of the `opencv-python` module in `requirements.txt`. The requirement has been updated to use the previous version of this module, as the version released a few days ago is incompatible with PyInstaller, which is used to generate the Windows executable.
=> Bug Fix: Module Incompatibilities

poetry.lock, pyproject.toml
Tested and figured out that the different python versions allowed is very important and clamping between 3.8 and 3.10 works the best.
All dependencies now go off name rather than git links (pyradiomics and matplotlib).
Most dependencies are just going off * for version to allow it to pick one that works.
Specific versions can be added in after getting a working version to make sure everyone is on the same setup.
=> Fixed Poetry and pyproject toml setup 

src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
Fixed a problem where the min and max density values were set as floats from transect but the program itself would not work with float but required them as integers. This fixes that and allows you to select in transect and not have to change before clicking draw.
=> Fixed float problem

src/View/BatchProcessingWindow.py, src/View/batchprocessing/ROINameCleaningOptions.py
Changes made here are in regards to ROINameCleaningOptions.py in src/View/batchprocessing/ where the requirement was to separate anatomy changes from GTV/CTV/PTV through the GUI by either different tabs or different tables. 
There was an issue where the wrong item would be suggested when changing ROI files, this has been changed but needs to be tested with more DICOM files before I can say it is fixed. But with what I have currently, it seems to run perfectly.
The choice was made that it would be displayed as two tables within the same tab so that when the tab is ticked it will run through the whole section. So if any of the ROIs need changing or don't need changing they will be considered together and changed together. With this choice there had to be double-ups in order to display both …
=> BatchProcessing - Seperate anatomy from GTV/CTV/PTV 

src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py, test/test_view_drawing.py
- Added a transparency slider to allow the drawn pixels in the draw ROI window to be adjust to allow users to see the original image pixels underneath what they have drawn. 
- Reworked how the existing draw functions coloured pixels to all use the same function that draws the pixels transparently. 
- Added a test to check that the transparency slider does change the pixels viewed by the user.
=> Draw ROI Transparency Slider #2351

src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
- Allowed the drawing tool cursor to be adjusted down to a 1 pixel diameter for precise drawing
- Changed the user facing elements to display the cursor size as diameter, to better reflect the new behaviour
- Note: Back end calculations still use radius, but it is converted to diamter to display to the user
=> Draw ROI Cursor Radius Fix #2408

src/View/batchprocessing/SelectSubgroupOptions.py
Assuming the first column in the clinical data is the Patient Identifier this will be removed from what is displayed in the filtering options table regardless of its name.
=> Removes the first column in the clinical-data-SR rather then hardcoding a column name

src/Controller/ROIOptionsController.py, src/View/mainpage/DrawROIWindow/SelectROIPopUp.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py, src/View/mainpage/StructureTab.py
In order to place the draw ROI window inside of the main Onko window, we must first move the step that allows the user to select an ROI.
This will instead be placed under a button on the draw ROI window, which will then trigger the original select ROI popup.
Logging has been introduced for newly added/modified methods.
No testing is present on this branch as no changes have been fundamentally made to the select ROI functionality. One thing that could be tested is the saving restriction, where the user must select an ROI type before saving. However, this is trivial within QT due to the use of popup messages/screens.
=> Select ROI GUI refactor

src/View/mainpage/DrawROIWindow/Drawing.py
Fixed draw ROI issue when manually drawing pixels with cursor.
This was due to the BFS source point being set as some form of float, causing the rest of the comparative array (which is used to determine if a pixel is coloured) to all be floats as well.
=> Fixed draw ROI issue when manaully drawing pixels with cursor

src/Model/batchprocessing/BatchProcessClinicalDataSR2CSV.py
Added a null check so the application does not crash for this BatchProcess when no SR files are found but rather behaves correctly and lets the user know that no files were found.
=> Added null check for dataset in patient_dict_container

src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py, test/test_view_drawing.py
- Added a fill button, linked to fill functionality (practically renamed from the old draw)
- Moved draw button, linked to drawing functionality
- Fixed the bug of not being able to fill more than once
=> Separated Fill and Draw Functionalities into Their Own Buttons #2444

src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py, src/View/mainpage/MainPage.py, test/test_view_drawing.py
Implemented windowing option for draw ROI page. This allows the user to change the windowing type whilst drawing a new ROI without loosing their progress.
=> Windowing draw roi #2452

src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
- Added automated hole-filling functionality when drawing ROIs.
- Functionality works for both 2D and 3D fills.
- When drawing to have holes be automatically filled enter an "internal hole size" greater than 0.
- To not have holes be automatically filled enter 0 for an "internal hole size" or leave the field blank.
- Also contains numerous fixes for a rebase error that occurred while adding 3D fill functionality.
=> Added Automated Hole-Filling Functionality When Drawing ROIs #2457

src/View/ProgressWindow.py, src/View/mainpage/DrawROIWindow/Drawing.py, src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
**Problem/Motivation**
When a user is using the 3d fill functionality, it displays no feedback to the user. This is not desirable and can cause the user to think the program has crashed
**Proposed Resolution**
Once the 3d fill has started processing, display some sort of processing feedback to the user (loading bar, etc)
=> Added 3D Fill Progress Window

.github/workflows/pythonapp.yml, requirements.txt, test/test_model_worker.py
v0.5 of OnkoDICOM is allowing up to Python 3.10, but there seem to be issues with 3.10 Local testing of installation and running OnkoDICOM 0.5.2 on Ubuntu 20.04 and 22.04 seemed OK with python 3.9
=> Update github workflow to use Python 3.9 for testing

pyproject.toml, src/Controller/MainPageController.py, src/View/AddOnOptions.py, src/View/OpenPatientWindow.py, src/View/addons/ImageFusionAddOnOption.py, src/View/mainpage/DicomAxialView.py, test/test_model_worker.py
Workaround: wrapping import of pymedphys with try/except due to recursive import that fails
Fix: eliminated casting of bitmask to int before applying bitwise OR 
Fix: wrapping initialisation of QSpacerItem with try/except to address signature variations
I'll investigate why the import of pymedphys is recursing in to areas of pymedphys that are not needed  for pseudonymisation, but for now the workaround will give the user an error when they try to pseudonymise rather than prevent them from launching OnkoDICOM at all,.
=> Fixes and workarounds needed to get 0.05.02-beta running on Ubuntu 20.04

.github/workflows/pythonapp.yml, README.md
Cache the test file (DICOM-RT-02.zip). This saves at least 3 minutes (sometimes 5 minutes) for each build.
Note: pip is not cached if we always want to use the **latest** version of packages
=> Cache test file

src/Model/CalculateDVHs.py
The current DVH.CSV export has columns in 'centiGray' and rows in '%'.
Change output to columns in '%' (100%, 99.5%, 99.0%, .....) and rows in 'centiGray' (no decimals, normal rounding). This will produce a spreadsheet with a fixed number of columns irrespective of the prescribed radiation dose.
=> Change DVH.CSV export: Change dvh output to percentvolume vs dose

src/View/mainpage/DicomView.py
1. Enable the scroll mouse / 2 finger scroll of the mouse tab scrolling through the CT layer (instead of up and down of a single CT picture)
2. Enable drag mode: Click the left mouse, then hold and drag to move the CT image
=> DICOM View Controller - Scrolling through CT layer + Drag and Drop CT image

src/Model/batchprocessing/BatchProcessDVH2CSV.py
The current DVH.CSV export has columns in 'centiGray' and rows in '%'.
Change output to columns in '%' (100%, 99.5%, 99.0%, .....) and rows in 'centiGray' (no decimals, normal rounding). This will produce a spreadsheet with a fixed number of columns irrespective of the prescribed radiation dose.
Change the export in BATCH Processing
=> Change DVH.CSV export: Change dvh output to percentvolume vs dose in BATCH Processing 

src/Model/ImageLoading.py
added RT Ion Plan SOP Class as one of the rtplan data types in the allowed_classes dictionary
closes #264
=> added RT Ion Plan SOP Class as one of the rtplan data types in the allowed_classes dictionary

src/Model/ImageLoading.py
accidentally left it uncommented as part of local testing
=> re-comment SliceLocation as a CT specific required attribute.
